### PR TITLE
Deploy Action

### PR DESCRIPTION
**Pull request by afrigon**

### CODE REVIEW

**Comment by masterT** [comment]
Why `node-version: [8.x, 10.x, 12.x]`?

**Comment by afrigon** [comment]
> Why `node-version: [8.x, 10.x, 12.x]`?

I don't know it's like that in the template action, im gonna make it just 12.x

**Comment by masterT** [comment]
Good! 

```
v12.13.0   (LTS: Erbium)
v12.13.1   (Latest LTS: Erbium)
```

**Comment by afrigon** [comment]
guess we need to merge to try it out ?

**Comment by masterT** [comment]
Maybe change the `name` for something more meaningful? Maybe "Deploy on GitHub Pages"?

**Comment by afrigon** [comment]
> Maybe change the `name` for something more meaningful? Maybe "Deploy on GitHub Pages"?

done @masterT

**Review by masterT — APPROVED** [review]
Good!

**Pull request merged**
